name: "Podcast generator"
author: "Ray Villalobos"
description: "Generate a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: The committer's email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{github.actor}}